### PR TITLE
feat: Modified Navbar

### LINKED ISSUE #141: Navbar Improvement
**Is your feature request related to a problem? Please describe.**
Currently, the Navbar of the website is looking kinda very simple, and to attract visitors to the website I think we need a good navbar.

**Describe the solution you'd like**
I would like to change the design of the Navbar.

**Describe alternatives you've considered**
I would make fonts a little fancier and would use a better colour pallet for the Navbar and would change it's design as well.

**Additional context**
I don't have any screenshots to provide but I have worked on this type of thing and would promise to give you the best result.

**Are you working on this? (Yes/No)**
Yes, I would like to work on this issue.

### PR DESCRIPTION
**Pull request by shawavisek35**
Fixes #141 

#### Changes done

- [ Modified Navbar ]

Screenshots of the changes (If any) -
Screenshot from 2021-03-26 19-03-38
Screenshot from 2021-03-26 19-03-46

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [ ] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
create a folder inside components and keep the NavBar.js file inside it change the relative imports Also and create one file Nav.css keep your css codes there don't modify the App.css

**Comment by shawavisek35** [comment]
> create a folder inside components and keep the NavBar.js file inside it change the relative imports Also and create one file Nav.css keep your css codes there don't modify the App.css and also ci checks are failing please see them and open an issue for your work and link it here

I will do the required changes. And about the CI error, i have added a search bar in the navbar which is animated and therefore the width of the search box is 0 and when you hover at te search icon it will become wider so the error is showing in the width : 0 part. Is there anything I can do to bypass this?

**Comment by ayan-biswas0412** [comment]
> > create a folder inside components and keep the NavBar.js file inside it change the relative imports Also and create one file Nav.css keep your css codes there don't modify the App.css and also ci checks are failing please see them and open an issue for your work and link it here
> 
> I will do the required changes. And about the CI error, i have added a search bar in the navbar which is animated and therefore the width of the search box is 0 and when you hover at te search icon it will become wider so the error is showing in the width : 0 part. Is there anything I can do to bypass this?

search stckoverflow

**Comment by shawavisek35** [comment]
@ayan-biswas0412 I have done the required changes. please review my PR and let me know anything needs to be corrected. :)

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
your navbar is completely invisible in dark mode please fix that

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Comment by shawavisek35** [comment]
Hey @ayan-biswas0412 can you please merge this pr as ot will automatically get closer due to inactivity by the bot

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please resolve conflicts

**Pull request closed without merging**
