### PR TITLE
feat: Add style to jumbotron

### PR DESCRIPTION
**Pull request by ankitaugale23**
Jumbotron was having minimal styling soo added some styling to it and its contents.
This will fix issue #104

Fixes #

1. Add the card type shadow effect to the jumbotron
2. Add Typing effect to the header of the jumbotron for laptop/desktop screen
3. Change the button color to black(so the GitHub can look better)
4. found the text on the button having spelling mistake so just fixed that(not mentioned in commit as it was a very minor change

**Added two libraries to package.json (react-socks) and (react-typewriter). 
- [ ]

Screenshots of the changes (If any) -
[https://drive.google.com/file/d/1DXyxdoeXY1zcAcmexaRzuCgOQmNZibbS/view?usp=sharing](url)
Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by ankitaugale23** [comment]
Let me know if any changes required further. @ayan-biswas0412

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
ci checks are failing please resolve them first

**Comment by aniketsingh98571** [comment]
@ankitaugale23 ` Unexpected whitespace at end of line (no-eol-whitespace) lines of code = 1
Found in hotelontouch\src\App.css:57
57
  letter-spacing: .001em; 
 Unexpected whitespace at end of line (no-eol-whitespace) lines of code = 1
Found in hotelontouch\src\App.css:53
53
  overflow: hidden; 
 Unexpected whitespace at end of line (no-eol-whitespace) lines of code = 1
Found in hotelontouch\src\App.css:58
58
  animation: 
 Unexpected whitespace at end of line (no-eol-whitespace) lines of code = 1
Found in hotelontouch\src\App.css:55
55
   white-space: nowrap; 
 Unexpected whitespace at end of line (no-eol-whitespace) lines of code = 1
Found in hotelontouch\src\App.css:54
54
  border-right: .10em solid black; `
Here is the error which you are getting, please remove the unnecessary whitespace....

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 I have also added some guidelines regarding the CI checks in the discussion section on the topic `CI/CD`, so in the readme.MD you can add this thing that `First read the CI/CD guidelines` to avoid failing of CI checks...

**Comment by ankitaugale23** [comment]
Sure. I will complete it and will edit the PR @aniketsingh98571 @ayan-biswas0412

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
don't commit the yarn.lock file

**Comment by ankitaugale23** [comment]
> don't commit the yarn.lock file

Done

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Comment by ankitaugale23** [comment]
> nice work

Thank you

**Pull request merged**
