### PR TITLE
feat: added register and login page

### PR DESCRIPTION
**Pull request by ooreally**
Fixes #

#### Changes done
added register and login page in hotelontouch whenever a user clicks on Register/Login  
resolved issue#132 which was opened by me.

Screenshots of the changes (If any) -

image

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by ooreally** [comment]
Hey! @ayan-biswas0412 please review this .

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
sign in page footer is not properly aligned

**Comment by ooreally** [comment]
Footer on the sign page aligned.

**Comment by ooreally** [comment]
Please review it @ayan-biswas0412

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
UI is nice now can you add login functionality and redirect user to  new blank page dashboard after login

**Comment by ooreally** [comment]
I need a login API in order to login a user. Please provide it to me @ayan-biswas0412

**Comment by ooreally** [comment]
@ayan-biswas0412 provide me login API if you want to connect to backend otherwise first merge this PR and then assign other issues.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
login api is available in the backend folder , run the backend folder via npm start you will get all the APIs

**Comment by ooreally** [comment]
@ayan-biswas0412 
I was getting following error:

const secret_key = process.env.JWT_SECRET || secret_key_for_jwt_token;                                              
^  ReferenceError: secret_key_for_jwt_token is not defined

then I created .env file , still getting an error:
Screenshot from 2021-05-19 23-58-43
Please direct me what to do.

**Comment by ooreally** [comment]
@ayan-biswas0412 Please merge this PR as frontend is ready and open another issue to connect to backend.

**Comment by ayan-biswas0412** [comment]
branch has immense conflicts

**Comment by ooreally** [comment]
@ayan-biswas0412  All conflicts have been resolved.

**Comment by ooreally** [comment]
@ayan-biswas0412 All the conflicts are resolved. Have a look .

**Pull request closed without merging**
