### PR TITLE
added Footer component and styles

### LINKED ISSUE #172: Improve footer UI
**Is your feature request related to a problem? Please describe.**
Improvements we can add to Footer are @ayan-biswas0412  :
1)Find us with logo
2)Call us with logo
3)Mail us with logo
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

**Are you working on this? (Yes)**

### PR DESCRIPTION
**Pull request by akshay1027**
Fixes #172 
Added 
1)Find us with logo
2)Call us with logo
3)Mail us with logo
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

Screenshots of the changes (If any) -
window size is at 80% so that you can see full design:

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [ ] Worked on forked repo and starred the main repo
- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by akshay1027** [comment]
@ayan-biswas0412 please check this out! I have spent a day making this Footer!! Please let me know your opinion

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
your footer Is looking completely absurd

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 I think there is no need to modify the footer, because:-
1. it is made using react-wavify so if we add anything that is a container it will break the whole structure.
2. as per the contents mentioned by @akshay1027  I think you will not need that much content like `subscribe`, `contact` and `find us`.

**Comment by akshay1027** [comment]
Yea you are correct, i tried but it did break the whole structure @aniketsingh98571 @ayan-biswas0412, i will try to modify existing footer itself, adding these many components wont work! Thanks

**Comment by akshay1027** [comment]
Before changes: 

- "contact me" heading is not aligned with "quick links" and "about project"!


2021-04-11 (8)_LI

- "about project" is not aligned properly!



After Changes:

- "contact me" heading is aligned with "quick links" and "about project".
-  "about project" is aligned properly in mobile UI.
-  added icons in "contact me".

**Comment by akshay1027** [comment]
If you approve this I shall make a new PR referencing this, @aniketsingh98571 @ayan-biswas0412, let me know what you think! Thank you!

**Comment by aniketsingh98571** [comment]
> If you approve this I shall make a new PR referencing this, @aniketsingh98571 @ayan-biswas0412, let me know what you think! Thank you!

please resolve the CI checks....

**Comment by akshay1027** [comment]
this is old PR, i will close this and make new one!

**Pull request closed without merging**
