### PR TITLE
Contributor section main website

### LINKED ISSUE #35: make All contributors section in main website
**Is your feature request related to a problem? Please describe.**
make a component inside ```src/components``` of folder ```hotelontouch``` , name the file ```AllContributors.js``` and the function name should be ```AllContributors``` and it should show the following information

1. Contributor Github Profile image
2. Github username => Clickable => Redirect to their profile
3. All contributors should be arranged in a way that old contributors remains on top
4. Component should be responsive to screen size

Render the component in HomeScreen
Use Github API to fetch the list of contributors of this repository
See the [website](https://doc2pen.smaranjitghose.codes) they have a contributors section

### PR DESCRIPTION
**Pull request by vinit-churi**
Fix #35 

#### Changes done
✅️ Created Contributor Github Profile image
✅️ Github Icon=> Clickable => Redirect to their profile
✅️ All contributors are arranged in a way that old contributors remains on top
✅️Component is made responsive to all size of screen.

Screenshots of the changes -

## desktop view:
image

## mobile view:

image

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by vinit-churi** [comment]
@ayan-biswas0412 check if the requirements are satisfied, suggest any changes if required.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
1. Please smaller the size of each image
2. give a small gap between every image
3. make the username clickable not just only the GitHub icon clickable and rest is fine

**Comment by vinit-churi** [comment]
@ayan-biswas0412 please check if the suggested changes done are satisfactory.

**Review by ayan-biswas0412 — APPROVED** [review]
good work

**Pull request merged**
