### PR TITLE
[Backend] Basic user endpoints added

### LINKED ISSUE #101: [Backend] Basic User Endpoints
### Issue Reference
[View Issue Reference](https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/issues/90#issuecomment-797267459)

### About this issue
The various operations or functionalities to be covered:
- CRUD users (as employee or customer)
- Hotel Room booking
- Admin routes to for making admin / removing admin (Users can only register as employees or customers. Only existing admins can add the admin role to others)

### PR DESCRIPTION
**Pull request by singhayushh**
Fixes #101 

#### Changes done

- [x] Following endpoints have been added:
  - register as customer or staff
  - login as customer or staff
  - fetch all customers
  - fetch all staff
  - fetch user by id or by email or by phone number
- [x] Swagger has been added for API documentation.
  - A separate `/docs` route has been created where all API descriptions are available along with success response body.

Screenshots of the changes (If any) -

**User Registration** - other routes have been tested as well
<kbd>
register
</kbd>

**API Documentation** - as seen under `/docs` route
<kbd>
image
</kbd>

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
1. employee can't be created using same phone or email

**Comment by singhayushh** [comment]
>     1. employee can't be created using same phone or email

@ayan-biswas0412 yes, I have added a check for that. 
Line 17 -> for customers and line 31 -> for employees in `controller/user.controller.js`

**Comment by singhayushh** [comment]
> @singhayushh I will merge your PR with first priority , please resolve the thing I have commented and ask for a review I will merge it

To make sure that no user registers as employee or customer with same phone number or email twice, I have set the email and phone number key to be unique in the mongo schema as well as provided a check whether the email or phone number exists in the database under the registering controller.
I hope the raised issue is resolved. 

For the check that is failing, variables from request body are needed for verifying the password and logging in the user. I have no clue why the check fails for using variables passed by the user.

**Comment by aniketsingh98571** [comment]
@singhayushh You can check at the particular checks by clicking on `details` link it will show you where your checks are failing, please look into it....

**Comment by singhayushh** [comment]
@aniketsingh98571 
Yes I did that. Only after checking the details, I came to know that the checking is failing because I'm using parameters that the user will pass. 

And not knowing why such a check causes failure, I commented the above.

**Comment by aniketsingh98571** [comment]
@singhayushh you can check on  StackOverflow for the issue.

**Comment by singhayushh** [comment]
@aniketsingh98571 All checks have passed. I hope the PR is all good now.

**Review by ayan-biswas0412 — APPROVED** [review]
I will surely merge it soon

**Pull request merged**
