### PR TITLE
added gssoc logo

### LINKED ISSUE #11: Add GSSoc 2021 logo in Readme
**Is your feature request related to a problem? Please describe.**
Add a logo of GSSoc 2021 in Readme file below the line we are now part of GSSoc 2021

**Describe the solution you'd like**
Follow proper markdown rules to add the logo and take the logo from GSSoc official website.
keep the logo as```docs/gsssoc2021_logo.png```

### PR DESCRIPTION
**Pull request by shreyanshi16**
Fixes #11 

#### Changes done

- [ ]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
your logo is not rendering properly

**Comment by shreyanshi16** [comment]
Can I directly drag and drop the image in the Readme file instead of making a docs folder and adding an image to it?

**Comment by ayan-biswas0412** [comment]
> Can I directly drag and drop the image in the Readme file instead of making a docs folder and adding an image to it?

you can see the wiki there is a GSSoc Logo we have used you can follow the same if you want to bypass the docs folder approach

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Pull request merged**
