### PR TITLE
Footer with wave animation add #28

### LINKED ISSUE #28: make a wave animation based footer
**Is your feature request related to a problem? Please describe.**
make a component inside ```src/components``` of folder ```hotelontouch``` , name the file ```Footer.js``` and the function name should be ```Footer``` and it should have the link to the the Github Repository

Make the footer which looks nice, new and creative ideas are most welcome

### PR DESCRIPTION
**Pull request by aniketsingh98571**
Fixes #28 

#### Changes done
Added footer component with wave animation using `react-wavify`

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 . please look into it.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
Some of the ci checks are failing please fix them

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 I have solved the issues, can you please check it.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
see there is a white gap and also I want all footer texts on the wave not like the current one keep the wave as the main footer component and render the texts icons on it , remove the static footer (the straight one)

**Comment by aniketsingh98571** [comment]
> see there is a white gap and also I want all footer texts on the wave not like the current one keep the wave as the main footer component and render the texts icons on it , remove the static footer (the straight one)

regarding the whitespace between footer and that box , so basically I have purposely kept the footer below because as the contents get added in between them so the footer will not change, it will adjust on itself and be at the bottom. And regarding the wave to be made as the main footer background, I will try to do it.

**Comment by ayan-biswas0412** [comment]
> > see there is a white gap and also I want all footer texts on the wave not like the current one keep the wave as the main footer component and render the texts icons on it , remove the static footer (the straight one)
> 
> regarding the whitespace between footer and that box , so basically I have purposely kept the footer below because as the contents get added in between them so the footer will not change, it will adjust on itself and be at the bottom. And regarding the wave to be made as the main footer background, I will try to do it.

yah and also try to remove the white space

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Please have a look at the changes made as per your need.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
again the white space is coming please fix it

**Comment by aniketsingh98571** [comment]
> again the white space is coming please fix it

can you please show me specific place where the whitespace is coming?

**Comment by ayan-biswas0412** [comment]
> > again the white space is coming please fix it
> 
> can you please show me specific place where the whitespace is coming?

https://deploy-preview-45--hotelontouch.netlify.app check this => check the bottom of the footer

**Comment by aniketsingh98571** [comment]
> > > again the white space is coming please fix it
> > 
> > 
> > can you please show me specific place where the whitespace is coming?
> 
> https://deploy-preview-45--hotelontouch.netlify.app check this => check the bottom of the footer

On which device are you talking about?

**Comment by aniketsingh98571** [comment]
Screenshot (113)
Here how it looks on laptop on max scroll.

**Comment by aniketsingh98571** [comment]
WhatsApp Image 2021-02-24 at 10 29 03 AM
Mobile view

**Review by ayan-biswas0412 — APPROVED** [review]
nice

**Pull request merged**
