### PR TITLE
Open source Section added #39

### LINKED ISSUE #39: make open source section in the website
**Is your feature request related to a problem? Please describe.**
Make one component open source programmes we are part of which can take a json as props the json should be as below
```js
let openSource = [
{
"name" : "Girlscript Summer of Code 2021",
"url" :"gesso.tech",
"logo" : "logo_url" // either from web or imported locally
}
]
```

**Describe the solution you'd like**
the component should be under ```hotelontouch/src/components``` and should be named ```OpensourceProgramme.js```

**Additional context**
You can use React Bootstrap Cards

### PR DESCRIPTION
**Pull request by aniketsingh98571**
Fixes #39 

#### Changes done
Added Open Source Programme section.
- [ ]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Please look into it and suggest if any changes needed.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
1. give my email (ayanbiswas184@gmail.com) at Contact Me (change it) in Footer
2.At abiut us give one line : ```In Todays Generation the Hotel Industries are changing rapidly so this platform will manage the in house needs of hotels like laundry service, Room Service Management, Bar, Restraunt Order Management.```

3. Keep only one card ```Girlscript Summer of Code``` and provide proper logo

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 , I think there is a problem with netlify because the details on netlify console are also not showing about the errors.

**Comment by ayan-biswas0412** [comment]
@aniketsingh98571 see the error

**Comment by ayan-biswas0412** [comment]
image
see the error @aniketsingh98571

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Please check it.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
1.Add a heading here (outside of the card) => ```We are part of```
2. Remove the mobile number from footer
3. Add some space on top of the github logo in footer

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 please have a look at the changes made.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
keep the contents of the footer section in a ```<Container/>```

**Comment by aniketsingh98571** [comment]
> keep the contents of the footer section in a `<Container/>`

@ayan-biswas0412  It's already enclosed in a container name `<body/>`

**Comment by ayan-biswas0412** [comment]
> > keep the contents of the footer section in a `<Container/>`
> 
> @ayan-biswas0412 It's already enclosed in a container name `<body/>`

in the mobile view some portion of the text is cutting please fix it then

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412, contents management has been managed, Please check it.

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Comment by aniketsingh98571** [comment]
> nice work

thanks

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 , As I have created 2 approved PR's so will it be counted for GSSoC 2021?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 , As I have created 2 approved PR's so will it be counted for GSSoC 2021?

yah I will merge this after 1 March , and I think from GSSoc official you can get the most updated info

**Comment by aniketsingh98571** [comment]
> > @ayan-biswas0412 , As I have created 2 approved PR's so will it be counted for GSSoC 2021?
> 
> yah I will merge this after 1 March , and I think from GSSoc official you can get the most updated info

Being a repo maintainer, it will be good if you can clear this doubt because I am just a participant so I cannot directly as them.

**Comment by ayan-biswas0412** [comment]
> > > @ayan-biswas0412 , As I have created 2 approved PR's so will it be counted for GSSoC 2021?
> > 
> > 
> > yah I will merge this after 1 March , and I think from GSSoc official you can get the most updated info
> 
> Being a repo maintainer, it will be good if you can clear this doubt because I am just a participant so I cannot directly as them.

see they are also changing some timeline i will surely ask them and let you know but as per official rule contributions from 1st march will be valid what i have heard from them but i will let you know when i have the updated info

**Pull request merged**
