### PR TITLE
Switchable dark mode functionality for website

### PR DESCRIPTION
**Pull request by Prajwal-ctrl**
Hey @ayan-biswas0412  Added Switchable dark mode functionality for website .....

Screenshot (74)

### CODE REVIEW

**Comment by Prajwal-ctrl** [comment]
is everything okay ? @ayan-biswas0412  please let me know what's the issue in PR , as this is my first commit so i don't know much about it , can you please guide me through it ?

**Comment by aniketsingh98571** [comment]
Screenshot (127)
@Prajwal-ctrl Here is the issue which you are getting, try to fix it...

**Comment by aniketsingh98571** [comment]
And also it will be good if you can replace `switch to dark` text with some cool SVG like `moon` or whatever you like....

**Comment by aniketsingh98571** [comment]
@Prajwal-ctrl `
 'FormControl' is defined but never used. lines of code = 1
Found in hotelontouch\src\components\NavbarComponent.js:6
6
import FormControl from '@material-ui/core/FormControl';
 'FormGroup' is defined but never used. lines of code = 1
Found in hotelontouch\src\components\NavbarComponent.js:4
4
import FormGroup from '@material-ui/core/FormGroup';
`

This is the error check again....

**Comment by aniketsingh98571** [comment]
@Prajwal-ctrl  change the color of `We are part of` and `contributors` text also during black theme.

**Comment by Prajwal-ctrl** [comment]
please let me know the changes for the dark theme

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
don't make it entirely black => make something dark blue and make the letters / texts white not red in dark mode

**Comment by ayan-biswas0412** [comment]
@aniketsingh98571 great effort 🥰 , I have seen you have reviewed many of PRs keep contributing

**Comment by Prajwal-ctrl** [comment]
> blue

@ayan-biswas0412 yeah , i also tried the same one  but if we make the text in a white color then the (Welcome) box color and text color do override with each other , so we have to change the text color other than white in dark mode 


Screenshot (83)

**Comment by Prajwal-ctrl** [comment]
@ayan-biswas0412  Can you please tell me the changes for the above one

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
still the colour scheme is not matching with the main style

**Comment by Prajwal-ctrl** [comment]
@ayan-biswas0412 yeah that's what i was trying to say is we just cant set the text color as a white because the background color of the welcome box is also the same and hence it doesn't look as i shared previous snapshot , so ..we have to change the text color to something else that matches with the dark background (black , blue ) color

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 yeah that's what i was trying to say is we just cant set the text color as a white because the background color of the welcome box is also the same and hence it doesn't look as i shared previous snapshot , so ..we have to change the text color to something else that matches with the dark background (black , blue ) color

yah do some good colours but please change the red one

**Comment by Prajwal-ctrl** [comment]
sure , Thanks 😀

**Comment by Prajwal-ctrl** [comment]
What about this one?

Screenshot (85)

**Comment by ayan-biswas0412** [comment]
> What about this one?
> 
> Screenshot (85)

not very impressive

**Comment by Prajwal-ctrl** [comment]
I just made a PR of this one , please review this one
Screenshot (88)

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please resolve conflicts first

**Comment by Prajwal-ctrl** [comment]
@aniketsingh98571 @ayan-biswas0412  can you please guide me through what actually i have to change or what to do exactly in those conflicts file

**Comment by aniketsingh98571** [comment]
@Prajwal-ctrl `FormControlLabel' is not defined. lines of code = 1
Found in hotelontouch\src\components\NavbarComponent.js:48
48
...FormControlLabel onClick={props.dark} value="end" control={<Switch color = "secondary" />} label="Change Theme...
 'projectRepository' is defined but never used. lines of code = 1
Found in hotelontouch\src\pages\HomePage.js:5
5
import { projectRepository } from '../data/projectData';
 'Jumbotron' is defined but never used. lines of code = 1
Found in hotelontouch\src\pages\HomePage.js:3
3
import { Container, Jumbotron, Button } from 'react-bootstrap';
 'Button' is defined but never used. lines of code = 1
Found in hotelontouch\src\pages\HomePage.js:3
3
import { Container, Jumbotron, Button } from 'react-bootstrap';`
Here is the error which you are getting please resolve it....

**Comment by Prajwal-ctrl** [comment]
sorry i mistakely made a wrong commit

**Comment by Prajwal-ctrl** [comment]
sorry i made some wrong commits

**Comment by Prajwal-ctrl** [comment]
@aniketsingh98571  @ayan-biswas0412  Is that final PR looks good ??

**Comment by ayan-biswas0412** [comment]
> @aniketsingh98571 @ayan-biswas0412 Is that final PR looks good ??

can you give a ss

**Comment by Prajwal-ctrl** [comment]
sure !
Screenshot (91)

**Comment by Prajwal-ctrl** [comment]
Screenshot (93)

**Review by ayan-biswas0412 — COMMENTED** [review]
where is the deploy preview link

**Comment by Prajwal-ctrl** [comment]
@aniketsingh98571  @ayan-biswas0412  which preview link ?? can you please share the screenshot of it

**Comment by Prajwal-ctrl** [comment]
Here is the Snapshot of the final Commit 
Screenshot (95)

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
this part should not be there
image

**Comment by Prajwal-ctrl** [comment]
@aniketsingh98571 @ayan-biswas0412  is everything okay in this PR ??
Screenshot (97)

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
again we are part of section colour not changing to white in dark mode

**Comment by Prajwal-ctrl** [comment]
How about this one ??
Screenshot (99)

**Comment by Prajwal-ctrl** [comment]
@aniketsingh98571 @ayan-biswas0412  Screenshot of the latest PR

**Comment by Prajwal-ctrl** [comment]
@aniketsingh98571 @ayan-biswas0412 Screenshot of the latest PR

Screenshot (101)

**Comment by Prajwal-ctrl** [comment]
@aniketsingh98571  @ayan-biswas0412  please review my last PR

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
now the work is good enough just change the button like this 
image
and your PR will be ready to merge

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 , I think the card of `we are part of` section should contain white borders, and the text color of `GSSoC` and `Contributors` should be white in my view...

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 , I think the card of `we are part of` section should contain white borders, and the text color of `GSSoC` and `Contributors` should be white in my view...

yah please make this a review comment

**Comment by Prajwal-ctrl** [comment]
@aniketsingh98571  yeah , i also tried the same one but if we make the text in a **White** colour then the (Welcome) box colour and the card colour of GSSOC and text colour(For White ) do override with each other , so we have to change the text colour other than white in **Dark mode**

Thats why i kept it Blue ....

**Comment by Prajwal-ctrl** [comment]
Hey @ayan-biswas0412  i tried to make a **switch** like you said but i can make upto this one 🙁
Screenshot (103)

**Comment by ayan-biswas0412** [comment]
> Hey @ayan-biswas0412 i tried to make a **switch** like you said but i can make upto this one 🙁
> Screenshot (103)

push it such that I can review

**Comment by Prajwal-ctrl** [comment]
What about the PR I made ? Please let me know

**Comment by Prajwal-ctrl** [comment]
@ayan-biswas0412 what about the PR I made ? Please let me know

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 what about the PR I made ? Please let me know

don't worry we value everyone's contribution

**Pull request closed without merging**
