### PR TITLE
Admin home page

### LINKED ISSUE #191: Home page in hotel-admin-frontend
**Describe the bug**
There is no page in hotel-admin-frontend i want to make home page under GSSoC'21 participant.

### PR DESCRIPTION
**Pull request by kumarishalini6**
Fixes #191

#### Changes done
I have made Home page for Hotel-admin-frontend

React App - Personal - Microsoft​ Edge 5_7_2021 09_59_14 PM

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
/about page is not discoverable and make the admin page more responsive and make a dashboard type layout

**Comment by kumarishalini6** [comment]
Now ,is every thing ok??
React App and 1 more page - Personal - Microsoft​ Edge 5_10_2021 10_17_05 PM

React App and 1 more page - Personal - Microsoft​ Edge 5_10_2021 10_16_01 PM
React App and 1 more page - Personal - Microsoft​ Edge 5_10_2021 10_16_17 PM
React App and 1 more page - Personal - Microsoft​ Edge 5_10_2021 10_16_50 PM

**Comment by kumarishalini6** [comment]
Please review my PR

**Comment by bhavita2404** [comment]
Can you improve the layout of dashboard.

**Comment by kumarishalini6** [comment]
Can you please explain in detail

**Comment by bhavita2404** [comment]
I mean try using any other layout which improves the outlook of the page.

**Comment by bhavita2404** [comment]
any updates ??

**Comment by kumarishalini6** [comment]
Ya working

**Comment by kumarishalini6** [comment]
But this issue is closed by the bot

**Comment by kumarishalini6** [comment]
Can I still work on it

**Pull request closed without merging**
