### PR TITLE
README.md updated

### PR DESCRIPTION
**Pull request by rajeshpanjiyar**
Fixes #

#### Changes done

- [ ]

Screenshots of the changes (If any) - 
image

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [✅️ ] Worked on forked repo and starred the main repo
- [ ✅️] Checked to see if a similar PR has already been opened 🤔️
- [ ✅️] Reviewed the contributing guidelines 🔍️
- [✅️ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ✅️] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
and also you are not assigned to this , please be patient , remember one thing : contributing in open source needs patience, before assignment don't rush and make PR as I can see you have not commented in the issue and raised 1 PR so this Is not acceptable

**Comment by rajeshpanjiyar** [comment]
Sorry sir unknowingly I might have done a mistake but I generated this pull request for the issue #Enhance the We are a part of section. Isn't this valid for that issue?

**Comment by rajeshpanjiyar** [comment]
And I am assigned to the issue #72

**Comment by ayan-biswas0412** [comment]
> And I am assigned to the issue #72

yeah I know but I told you to try for a fresh issue rather than working on an issue from before of assigning , its ok for first time

**Pull request closed without merging**
