### PR TITLE
Title has been added check once

### PR DESCRIPTION
**Pull request by Ruchip16**
Fixes #

#### Changes done

- [ ]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [ ] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
ci checks are failing please resolve them

**Comment by Ruchip16** [comment]
Ok ci checks means ??

**Comment by ayan-biswas0412** [comment]
> Ok ci checks means ??

see below it is saying some checks are failing

**Comment by aniketsingh98571** [comment]
> Ok ci checks means ??

@Ruchip16 CI means Continous Integration.....It basically checks whether your code is good enough in terms of good practices of writing code, if your code will be merged to the main then it will not affect the whole project structure, and so on... CI is a deep concept under DevOps and it's mostly used to automate tasks which GitHub uses a lot...

**Comment by aniketsingh98571** [comment]
@Ruchip16 `
 'renderCard' is assigned a value but never used. lines of code = 1
Read Up
Found in hotelontouch\src\components\AdminCard.js:63
63
const renderCard = (card, index) => {
`
this is the error which you are getting please fix it...

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
ci checks are failing

**Comment by Ruchip16** [comment]
> @Ruchip16 `'renderCard' is assigned a value but never used. lines of code = 1 Read Up Found in hotelontouch\src\components\AdminCard.js:63 63 const renderCard = (card, index) => {`
> this is the error which you are getting please fix it...

**Comment by Ruchip16** [comment]
@ayan-biswas0412  Ya I will fix that issue

**Comment by Ruchip16** [comment]
@aniketsingh98571  but I am not able to understand where should I call rendercard

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
resolve the conflicts please

**Comment by Ruchip16** [comment]
@ayan-biswas0412  I have added title check now

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
pleas resolve the conflicts first

**Comment by Ruchip16** [comment]
@ayan Biswas can u please elaborate on which changes do I need to make or put some screenshots or something like that so that I can work there it would be very much helpful coz u said you will review or suggest changes only after making a PR so plz elaborate

**Pull request closed without merging**
