### PR TITLE
login form created

### LINKED ISSUE #43: make a login page in hotel-admin-frontend
**Is your feature request related to a problem? Please describe.**
make one login page inside ```hotel-admin-frontend/src/pages``` and name it ```Login.js``` use React Bootstrap forms
there should be the following fields

1.Username
2.Password
3.Captcha Validation
4. Proper validation check for Valid Email formats in the ```Username``` Field
5. If captcha is not done then form can't be submitted 
6. On Successful submission print the formdata in consul.log

### PR DESCRIPTION
**Pull request by Sapna2001**
Fixes #43 

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please fix the ci tests first

**Comment by Sapna2001** [comment]
@ayan-biswas0412 it was failing because the password was being displayed in the console. I have removed console.log for password. Is it fine?

**Comment by Sapna2001** [comment]
@ayan-biswas0412 I have removed the console log for the password. Any other change required?

**Review by ayan-biswas0412 — COMMENTED** [review]
can you please tell how to test this ? like how to test your login form

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 you can test it by using it in the index.js. Do you want me to change the color? Are you looking out for any specific layout?

yah actually I am looking for more eye catchy solution and for testing I mean what is the credentials of the form (any hardcoded)

**Comment by Sapna2001** [comment]
> yah actually I am looking for more eye catchy solution and for testing I mean what is the credentials of the form (any hardcoded)

You can test it here : https://www.google.com/recaptcha/admin/site/443803173

I have given you access (ayanbiswas184@gmail.com)

I will work on making it catchy.

**Pull request closed without merging**
