### PR TITLE
Added an app launching page in hotelontouch

### LINKED ISSUE #123: Create a app launching page in hotelontouch
**Is your feature request related to a problem? Please describe.**
make a page /applaunch inside hotelontouch
the page should describe app of hotelontouch you may use cool svgs and make it creative and all components should reside under /components

### PR DESCRIPTION
**Pull request by AshuKV**
Fixes #123 

#### Changes done

- [ ]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
I don't think you have done anything good and lot of changes is in the index.html but in react app development we do not do anything inside public folder and do all our work mainly in src please tell that how I can test your work ?

**Comment by AshuKV** [comment]
image
image
image
image
image

**Review by AshuKV — COMMENTED** [review]
Hey @ayan-biswas0412  you can add this content as a template

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
this is a react site , please follow the guidelines of react development

**Comment by AshuKV** [comment]
Ok @ayan-biswas0412 I am closing this PR. I would start working to build this app launching page using React now.

**Pull request closed without merging**
