### PR TITLE
Admin Card

### LINKED ISSUE #69: Add a title project admin
**Is your feature request related to a problem? Please describe.**
Add a title project admin before the picture of the project admin edit the ```hotelontouch/src/components/AdminCard.js```
and make UI improvement of the card if possible more interactive designs are welcome

### PR DESCRIPTION
**Pull request by Ankita297**
Fixes #69 

I have added a title above admin picture and i have also made some changes in UI of of admin card .
#### Changes done

- [ ]

Screenshots of the changes (If any) -

https://user-images.githubusercontent.com/67833077/113503596-85399d80-9550-11eb-95fd-5ca872bb0433.mp4

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x ] Worked on forked repo and starred the main repo
- [ x] Checked to see if a similar PR has already been opened 🤔️
- [x ] Reviewed the contributing guidelines 🔍️
- [x ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by Ankita297** [comment]
@ayan-biswas0412  Please review the PR and if other changes required  Please tell me .

**Comment by Ankita297** [comment]
@ayan-biswas0412  can you increase the level of issue ?

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please make the photo length such that it covers some aspect my the waves

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 can you increase the level of issue ?

no

**Comment by Ankita297** [comment]
HotelOnTouch - Google Chrome 07-04-2021 08_09_40
HotelOnTouch - Google Chrome 07-04-2021 08_09_45

**Comment by Ankita297** [comment]
@ayan-biswas0412  is it okay now ?

**Comment by Ankita297** [comment]
@ayan-biswas0412 is it okay now ?

**Review by ayan-biswas0412 — COMMENTED** [review]
@aniketsingh98571 can you review it

**Comment by aniketsingh98571** [comment]
> @aniketsingh98571 can you review it

@Ankita297 @ayan-biswas0412 Here is my views on it:-
1.Name `Ayan Biswas` is repeated twice so it will be better if you just keep it on a single instance.
2. See every time it's not necessary to add wave animation, it is specifically designed for only footers I don't understand why everyone is using in cards....in my way it's not looking nice.
3. There is whitespace between ayan's pic and wave animation.
Overall I would suggest it change the design and be more creative.

**Comment by Ankita297** [comment]
Okay @aniketsingh98571  I will change it .

**Comment by Ankita297** [comment]
Uploading final_607463b84373410086785463_777996.mp4…

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/114419447-105e0780-9bd1-11eb-8f6e-ab77e744fe9a.mp4

**Comment by Ankita297** [comment]
@ayan-biswas0412 @aniketsingh98571 is it okay ?
Or need  changes ?

**Comment by aniketsingh98571** [comment]
> @ayan-biswas0412 @aniketsingh98571 is it okay ?
> Or need changes ?
It's fine for me good work.

**Comment by Ankita297** [comment]
@aniketsingh98571  can level of this issue be 2 I am just asking ?

**Comment by Ankita297** [comment]
@ayan-biswas0412  @aniketsingh98571  is it okay to be merged
?

**Comment by Ankita297** [comment]
@ayan-biswas0412 @aniketsingh98571 the PR is staling .
Please review it . I have done alot in this .
Please add it .

**Comment by Ankita297** [comment]
Also i have request if you can change its level to 2 .
Otherwise its okay

**Comment by Ankita297** [comment]
let me check @ayan-biswas0412 .

**Comment by Ankita297** [comment]
@ayan-biswas0412 Please see now . is it okay .By mistake i have made the opacity 0 .
Sorry .

**Comment by Ankita297** [comment]
@ayan-biswas0412  Please review it now ?

**Comment by Ankita297** [comment]
Please review it @ayan-biswas0412 Sir .

**Comment by Ankita297** [comment]
Please review  it  @ayan-biswas0412 Sir .

**Comment by Ankita297** [comment]
@ayan-biswas0412 Sir Please review my PR .

**Comment by Ankita297** [comment]
@ayan-biswas0412  SIr can you please review my PR .

**Pull request closed without merging**
