### PR TITLE
Now it's working HotelOnTouch website

### PR DESCRIPTION
**Pull request by Vi1234sh12**
Signed-off-by: Vishal Dhanure <vishald41234@gmail.com>

Fixes #

#### Changes done

- [ ]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [ ] Worked on forked repo and starred the main repo
- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
can you give proper context why you have raised this PR

**Comment by Vi1234sh12** [comment]
> can you give proper context why you have raised this PR

Actually, I thought the problem is solved that's the reason I'm raised PR  
If Any Work is Remaining please let me know  I will Take an Issue 

Thanks 
Vishal Dhanure

**Comment by ayan-biswas0412** [comment]
> > can you give proper context why you have raised this PR
> 
> Actually, I thought the problem is solved that's the reason I'm raised PR
> If Any Work is Remaining please let me know I will Take an Issue
> 
> Thanks
> Vishal Dhanure

can you tag proper issue ? in which this is relevant

**Comment by ayan-biswas0412** [comment]
@Vi1234sh12 please tell which issue you are trying to solve ?

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please tell which issue are you trying to solve

**Comment by ayan-biswas0412** [comment]
Invalid PR

**Pull request closed without merging**
