### PR TITLE
Improved welcome to project section.

### PR DESCRIPTION
**Pull request by padmajabhol**
Changed backgrounds,buttons,fonts,etc.

Fixes #

1.Added a background image
2.Animated the button
3.Changed fonts
4.Added shadow
5.Aligned items to center.
#71 
Screenshot (4)

- [ ]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [ ] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
you are supposed to change the WelcomeCard only and not supposed to do anything in the HomePage , major rework is required , the entire structure got distorted

**Comment by padmajabhol** [comment]
> you are supposed to change the WelcomeCard only and not supposed to do anything in the HomePage , major rework is required , the entire structure got distorted

I thought you wanted changes in the Jumbotron div, and not just the <h1> tag, this is somewhat confusing.

**Comment by ayan-biswas0412** [comment]
> > you are supposed to change the WelcomeCard only and not supposed to do anything in the HomePage , major rework is required , the entire structure got distorted
> 
> I thought you wanted changes in the Jumbotron div, and not just the
> 
> # tag, this is somewhat confusing.

no jumbotron is absolutely fine i want changes in WelcomeCard

**Comment by padmajabhol** [comment]
> > > you are supposed to change the WelcomeCard only and not supposed to do anything in the HomePage , major rework is required , the entire structure got distorted
> > 
> > 
> > I thought you wanted changes in the Jumbotron div, and not just the
> > # tag, this is somewhat confusing.
> 
> no jumbotron is absolutely fine i want changes in WelcomeCard

I cant find it, can you attach a screenshot?

**Comment by aniketsingh98571** [comment]
@padmajabhol ` 'Button' is defined but never used. lines of code = 1
Found in hotelontouch\src\pages\HomePage.js:2
2
import { Container, Button } from 'react-bootstrap';
 'projectRepository' is defined but never used. lines of code = 1
Found in hotelontouch\src\pages\HomePage.js:4
4
import { projectRepository } from '../data/projectData';` This is the error you are getting please fix it....

**Comment by ayan-biswas0412** [comment]
> @padmajabhol ` 'Button' is defined but never used. lines of code = 1 Found in hotelontouch\src\pages\HomePage.js:2 2 import { Container, Button } from 'react-bootstrap'; 'projectRepository' is defined but never used. lines of code = 1 Found in hotelontouch\src\pages\HomePage.js:4 4 import { projectRepository } from '../data/projectData';` This is the error you are getting please fix it....

@padmajabhol please do this changes

**Comment by aniketsingh98571** [comment]
@padmajabhol ` 'Button' is defined but never used. lines of code = 1
Found in hotelontouch\src\pages\HomePage.js:2
2
import { Container, Button } from 'react-bootstrap';
 'projectRepository' is defined but never used. lines of code = 1
Found in hotelontouch\src\pages\HomePage.js:4
4
import { projectRepository } from '../data/projectData';`
Here is the error which you are getting....Please resolve it and also
you have changed the entire project structure...please work on the particular section on which you have assigned.

**Pull request closed without merging**
