### PR TITLE
Solution Section created

### LINKED ISSUE #55: Add our Solutions Section in the main website
**Is your feature request related to a problem? Please describe.**
make the component inside ```hotelontouch/src/components``` , Give the name ```OurSolution.js``` and use good svgs and small description (refer Readme) about the three project modules 

1. Hotel Guest App 
2. Hotel Admin App 
3. Hotel Services End App

### PR DESCRIPTION
**Pull request by aniketsingh98571**
Fixes #55 

#### Changes done

- [x]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Please have a look and also I have changed the SVG's as per your directions...do suggest if any changes needed

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
instead of redirecting to GitHub repo redirect to this links
https://restraunt-hotelontouch.netlify.app
https://admin-hotelontouch.netlify.app
for the customer section keep it Github Repo

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Added the required links...

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
you have swapped the links of Guest End and service end

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 I have swapped the link please look into it.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please resolve merge conflict

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 All links have changed please check,

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
Guest App should return here https://github.com/ayan-biswas0412/gssoc2021-HotelOnTouch/tree/main/customerfrontend

**Comment by aniketsingh98571** [comment]
@ayan-biswas0412 Necessary changes have been made...

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Pull request merged**
