### PR TITLE
Enhance the we are part of section

### LINKED ISSUE #72: Enhance the We are a part of section
**Is your feature request related to a problem? Please describe.**
1. Enlarge the text size of the We are a part of 
2. Make style improvements in the section, use some cool animations if possible

### PR DESCRIPTION
**Pull request by Ankita297**
Fixes #72

#### Enhance the we are part of section

- [x ]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [ x] Worked on forked repo and starred the main repo
- [x ] Checked to see if a similar PR has already been opened 🤔️
- [x ] Reviewed the contributing guidelines 🔍️
- [ x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ x] Tried Squashing the commits into one

https://user-images.githubusercontent.com/67833077/111021795-ec05e400-83f4-11eb-8d9a-943c174e8404.mp4

### CODE REVIEW

**Comment by aniketsingh98571** [comment]
Screenshot (126)
@Ankita297 Here is the issue which you are getting.....

If you are not using `Button` in your code then remove it.....

**Comment by aniketsingh98571** [comment]
And also it would be good if you can bring that wave animation on the bottom of the cards...it doesn't suit to float up, otherwise, you can choose some good animation for it...overall the styling is good...

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
match the theme with website like use the wave colour bluish to blackish

**Comment by Ankita297** [comment]
like the footer color ?

**Comment by aniketsingh98571** [comment]
> like the footer color ?

use the theme of the website like `blue color or its shades`....and also bring the wave to the bottom section

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111035151-17152580-843f-11eb-9465-6ba925a08f32.mp4

**Comment by Ankita297** [comment]
is it okay now ?

**Comment by aniketsingh98571** [comment]
> is it okay now ?

instead of wave animation, you can also provide a nice hover effect on the card, wave animation is not suiting the card currently in my opinion, but it all depends on the reaction of @ayan-biswas0412.

**Comment by ayan-biswas0412** [comment]
> > is it okay now ?
> 
> instead of wave animation, you can also provide a nice hover effect on the card, wave animation is not suiting the card currently in my opinion, but it all depends on the reaction of @ayan-biswas0412.

yah I think it will be better

**Comment by ayan-biswas0412** [comment]
> > > is it okay now ?
> > 
> > 
> > instead of wave animation, you can also provide a nice hover effect on the card, wave animation is not suiting the card currently in my opinion, but it all depends on the reaction of @ayan-biswas0412.
> 
> yah I think it will be better @Ankita297

**Comment by Ankita297** [comment]
https://user-images.githubusercontent.com/67833077/111071759-aaad2b80-84fd-11eb-9f95-30bf0d1d38ba.mp4

**Comment by Ankita297** [comment]
is it okay now ?

**Comment by Ankita297** [comment]
is it okay now ?

**Comment by Ankita297** [comment]
I have  not made any commit now .if it is okay then i will  add the commit .

**Comment by ayan-biswas0412** [comment]
> I have not made any commit now .if it is okay then i will add the commit .

nice push your commit

**Comment by Ankita297** [comment]
Done Sir.

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Pull request merged**
