### PR TITLE
Added applaunch Page, fixes issue #123

### LINKED ISSUE #123: Create a app launching page in hotelontouch
**Is your feature request related to a problem? Please describe.**
make a page /applaunch inside hotelontouch
the page should describe app of hotelontouch you may use cool svgs and make it creative and all components should reside under /components

### PR DESCRIPTION
**Pull request by abhishek7997**
type: fix

Fixes #123 

#### Changes done

- [1] Added AppLaunch.js in components folder
- [2] Added '/applaunch' route in App.js
- [3] Added AppLaunch.js page in '/pages' and in 'index.js'

Screenshots of the changes (If any) -

image
image

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by abhishek7997** [comment]
@ayan-biswas0412 Sir please check my PR as well

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
why no deploy previews are not created by netlify ? can you debug ?

**Comment by abhishek7997** [comment]
> why no deploy previews are not created by netlify ? can you debug ?

@ayan-biswas0412 Sir, I don't know what this netlify thing, or the checks are, or how they work, please help.

**Comment by ayan-biswas0412** [comment]
> > why no deploy previews are not created by netlify ? can you debug ?
> 
> @ayan-biswas0412 Sir, I don't know what this netlify thing, or the checks are, or how they work, please help.

when you raise a PR netlify builds deploy preview automatically but in your case no deploy preview is created so I am unable to test your PR

**Comment by abhishek7997** [comment]
@ayan-biswas0412 Sir, I have no idea how to go about this. Should I delete my forked repo and fork and clone a new one and make a new PR? I believe you can check what all files have been changed in all of my 5 commits. Please check them and tell what should I do next.

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Sir, I have no idea how to go about this. Should I delete my forked repo and fork and clone a new one and make a new PR? I believe you can check what all files have been changed in all of my 5 commits. Please check them and tell what should I do next.

yah you can do that

**Comment by abhishek7997** [comment]
Should I close this PR then?

**Comment by abhishek7997** [comment]
@ayan-biswas0412 Please check my new PR

**Pull request closed without merging**
