### PR TITLE
adding ContactUs component with react-boostrap and using in custom us…

### LINKED ISSUE #38: Make Contact us form
**Is your feature request related to a problem? Please describe.**
Make one blank contact us form which takes the following inputs
1.Name 
2. Email
3. Message

**Describe the solution you'd like**
Make the component inside ```hotelontouch/src/components``` and name the component ```ContactUs.js``` the component should be good looking , more innovative ideas are welcome

**Additional context**
Use React Bootstrap Forms and give proper validation checks , ignore the form action part for now there should be blank action url for POST Request of the json , for now after form submit show the json in ```console.log```

### PR DESCRIPTION
**Pull request by Doringl**
Fixes #38 

Changes proposed in this pull request :

adding ContactUs component with react-bootstrap (rendering in HomePage for testing, if you want to create ContactUs page with routing I can fix it),
adding custom useForm hook for getting values from form (advice ... we can seperate custom hook to `hotelontouch/src/hooks`)
using inline style for some styling (styled-components can be used)
@ayan-biswas0412/gssoc2021-HotelOnTouch

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
looks good now can you improve the UI because currently it is coming as full page but it should not be that much big and make responsive for mobile also and we are intending to integrate it with form spree later before that give proper validation checks (success => green and warning in red colour for invalid entries)

**Comment by Doringl** [comment]
I can fix ui in ContactUs page also we can use react-hook-form instead using custom useForm hook

**Comment by ayan-biswas0412** [comment]
> I can fix ui in ContactUs page also we can use react-hook-form instead using custom useForm hook

yah sure you can use that also

**Comment by Doringl** [comment]
you can close here ...

**Comment by ayan-biswas0412** [comment]
> you can close here ...

where is the form can you give me screenshot from deployed version

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
still now it is not visible

**Pull request closed without merging**
