### PR TITLE
Added ContactUs Page

### LINKED ISSUE #38: Make Contact us form
**Is your feature request related to a problem? Please describe.**
Make one blank contact us form which takes the following inputs
1.Name 
2. Email
3. Message

**Describe the solution you'd like**
Make the component inside ```hotelontouch/src/components``` and name the component ```ContactUs.js``` the component should be good looking , more innovative ideas are welcome

**Additional context**
Use React Bootstrap Forms and give proper validation checks , ignore the form action part for now there should be blank action url for POST Request of the json , for now after form submit show the json in ```console.log```

### PR DESCRIPTION
**Pull request by shreyanshi16**
Fixes #38

#### Changes done

- [Added Contact Us Page ]

Screenshots of the changes (If any) -
image

Filling empty Name, Email, and Message-
image

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x ] Worked on forked repo and starred the main repo
- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
after deployment page is missing

**Comment by shreyanshi16** [comment]
Please see if you can access now ContactUsPage with /contact route

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Comment by shreyanshi16** [comment]
Thank you!

**Pull request merged**
