### PR TITLE
setup React router and bootstrap  for hotel-restraunt-frontend

### LINKED ISSUE #16: setup React router for hotel-restraunt-frontend
**Describe the solution you'd like**
Add routes for different pages make page_one.js and page_two.js and define their corresponding routes under ```src/App.js``` and also integrate [React Bootstrap](https://react-bootstrap.github.io)

all pages should be under ```src/pages```

show one bootstrap <Card> in both of the pages containing text like ```This is the page one```

**Describe alternatives you've considered**

**Additional context**
NA

### PR DESCRIPTION
**Pull request by vinit-churi**
Fix #16 

#### Changes done
- [x] Add routes for different pages make PageOne.js and PageTwo.js and define their corresponding routes under src/App.js and also integrate React Bootstrap
- [x] all pages should be under src/pages
- [x] show one bootstrap in both of the pages containing text like "page 1 Welcome"

#### Screenshots
image
this is my first pr, please provide any advice if done anything wrong

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
CI tests are failing please fix that

**Comment by vinit-churi** [comment]
@ayan-biswas0412 can you please advice me on how to debug this. or the reason why the test are failing. I haven't modified anything unrelated to required feature 
image

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 can you please advice me on how to debug this. or the reason why the test are failing. I haven't modified anything unrelated to required feature
> image

please see the ```hotelontouch``` folder and do your work according to that and then see the deploy log carefully

**Comment by vinit-churi** [comment]
@ayan-biswas0412 sorry for bothering you, but I was curious about why the default exports changed to named exports?
and have I cleared all the test? it's still showing that 11 neutral test remaining

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 sorry for bothering you, but I was curious about why the default exports changed to named exports?
> and have I cleared all the test? it's still showing that 11 neutral test remaining, please suggest if any changes are needed.

yah neutral testing checks is ok but failed tests is not accepted , anyways thank you for solving the checks issue.😅

**Review by ayan-biswas0412 — APPROVED** [review]

**Pull request merged**
