### PR TITLE
added label in documentation

### LINKED ISSUE #57: Add this label at the start of the Readme
**Is your feature request related to a problem? Please describe.**

[CodeFactor](https://www.codefactor.io/repository/github/ayan-biswas0412/gssoc2021-hotelontouch)

Just copy the below text to get the label
```
[![CodeFactor](https://www.codefactor.io/repository/github/ayan-biswas0412/gssoc2021-hotelontouch/badge)](https://www.codefactor.io/repository/github/ayan-biswas0412/gssoc2021-hotelontouch)
```
Add it at the first of the Readme file

### PR DESCRIPTION
**Pull request by tanay13**
Fixes #57 

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Comment by tanay13** [comment]
@ayan-biswas0412  please review this

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please remove the ```.yarn-integrity``` and the ```yarn.lock``` file

**Comment by tanay13** [comment]
> please remove the `.yarn-integrity` and the `yarn.lock` file

Now please check it again

**Review by ayan-biswas0412 — APPROVED** [review]
good work

**Pull request merged**
