### PR TITLE
adding admincard component with react-bootstrap...

### LINKED ISSUE #37: Make a Project Admin Card Component
**Is your feature request related to a problem? Please describe.**
Add a project admin card component the card should contain 
Project Admin Name : Ayan Biswas , Github Username : ayan-biswas0412 , Website : https://ayanbiswas.in and fetch the GitHub profile picture for the card

Name the component ```AdminCard.js``` , keep this in ```hotelontouch/src/components``` and render it in ```HomePage.js```

**Describe the solution you'd like**
Use React Bootstrap Cards and make a good looking card  
Innovative ideas are most welcome

### PR DESCRIPTION
**Pull request by Doringl**
Fixes #37 

Changes proposed in this pull request :

adding AdminCard component with react-bootstrap ,
rendering in HomePage ...
@ayan-biswas0412/gssoc2021-HotelOnTouch

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
1. Give a heading Project Admin 
2. Add Github Logo => Onclick => go to the profile ```https://github.com/ayan-biswas0412```
3. Make the card centre to the page
4. Add some cool animations if possible

**Comment by Doringl** [comment]
Give a heading Project Admin ✔
Add Github Logo => Onclick => go to the profile https://github.com/ayan-biswas0412 ✔
Make the card centre to the page ✔
Provide a logo of Web instead of Website Button ✔
Add some cool animations if possible ✔

**Comment by Doringl** [comment]
I hope you like my works ... 😎

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please make the card size a little bit smaller and do not write the Project Admin inside card keep it as a section heading 
and also fix the web logo as it is not rendering 
image

And don't make css as another file please put it In AdminCard.js , you can use styled-components package to declare css inside the js file

**Comment by Doringl** [comment]
I can do that but now i m busy a bit.

**Comment by ayan-biswas0412** [comment]
> I can do that but now i m busy a bit.

Sure take your time

**Comment by Doringl** [comment]
Ekran Alıntısı

logo rendering for me ?

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
@Doringl can you please resolve the conflicts

**Comment by Doringl** [comment]
you merged in the wrong order, please when an issue completed merge them, dont wait .

**Comment by ayan-biswas0412** [comment]
> you merged in the wrong order, please when an issue completed merge them, dont wait .

yeah your contribution is in the code but why this PR is open i don't know , i was waiting for the gssoc timeline so i merged it later

**Comment by ayan-biswas0412** [comment]
> you merged in the wrong order, please when an issue completed merge them, dont wait .

yes I found the problem actually when you have contributed to this that particular branch is not similar to your current forked main branch so it becomes a patch and now this contribution seems to be invalid, always wait (before rewokring or deleting on a branch from which an active PR exists) till somebody merges your changes.

**Comment by Doringl** [comment]
there is no resolve conflict button also, i think dont need to resolve because admincard component is in the project.

**Comment by Doringl** [comment]
> there is no resolve conflict button also, i think dont need to resolve because admincard component is in the project.

**Comment by ayan-biswas0412** [comment]
> there is no resolve conflict button also, i think dont need to resolve because admincard component is in the project.

i know ...because you have reworked on the base branch of this PR and made another PRs from that so it happened

**Comment by ayan-biswas0412** [comment]
> > you merged in the wrong order, please when an issue completed merge them, dont wait .
> 
> yes, I found the problem actually when you have contributed to this that particular branch is not similar to your current forked main branch so it becomes a patch and now this contribution seems to be invalid, always wait (before reworking or deleting on a branch from which an active PR exists) till somebody merges your changes.
> 
> if you want to make this PR to be merged please checkout from the updated main then add your changes and make a separate PR I will merge that

see this @Doringl

**Pull request closed without merging**
