### PR TITLE
Integrating ContactUsPage, fixing contactus compnent ui and adding react-hook-form with error handling ... 

### LINKED ISSUE #38: Make Contact us form
**Is your feature request related to a problem? Please describe.**
Make one blank contact us form which takes the following inputs
1.Name 
2. Email
3. Message

**Describe the solution you'd like**
Make the component inside ```hotelontouch/src/components``` and name the component ```ContactUs.js``` the component should be good looking , more innovative ideas are welcome

**Additional context**
Use React Bootstrap Forms and give proper validation checks , ignore the form action part for now there should be blank action url for POST Request of the json , for now after form submit show the json in ```console.log```

### PR DESCRIPTION
**Pull request by Doringl**
Fixes #38

Changes proposed in this pull request :

adding ContactUs component with react-bootstrap
adding react-hook-form
@ayan-biswas0412/gssoc2021-HotelOnTouch

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
@Doringl your page is not accessible in deploy preview you can take help from here I think https://sung.codes/blog/2018/12/18/page-not-found-on-netlify-with-react-router/ or research on this error more
you may open a separate issue on this and work in this

**Comment by Doringl** [comment]
you can access now ContactUsPage with /contact route ...

**Comment by ayan-biswas0412** [comment]
> you can access now ContactUsPage with /contact route ...

no it is still not accessable see https://deploy-preview-96--hotelontouch.netlify.app/contact

**Comment by Doringl** [comment]
I think you need add redirects file

**Comment by ayan-biswas0412** [comment]
> I think you need add redirects file

please do the needful

**Comment by Doringl** [comment]
redirect rules succesfull for hotelontouch.

**Comment by Doringl** [comment]
sorry unassign me.

**Comment by ayan-biswas0412** [comment]
> sorry unassign me.

it is not an issue 😅 it is your PR how can I unassign you, if you are in a shortage of time it's ok bro

**Comment by Doringl** [comment]
your right :) sorry im busy nowadays i cant focus.

**Pull request closed without merging**
