### PR TITLE
ADDED Dark Mode

### LINKED ISSUE #94: Switchable Dark Mode for website
Hi @ayan-biswas0412 @shreyanshi16 i'm a GSSOC 21 participant can i work on this issue ? please let me know

### PR DESCRIPTION
**Pull request by mohammedjameel24**
Fixes #94 
## About The PR
This PR is For Adding Dark mode UI to the customer end of the Webpage

**what all has been done in this pull request**
Added Toggle for dark / light theme modes

**File Changes**
directory : hotelontouch ->src -> App.js
                                          public -> index.html

**Preview Link**
https://deploy-preview-128--hotelontouch.netlify.app/

Screenshots of the changes (If any) -
## Before
Screenshot 2021-03-17 202711
## After
Screenshot 2021-03-17 202835

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [ ] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by mohammedjameel24** [comment]
please review my pull request @ayan-biswas0412

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
ci checks are failing please fix them

**Comment by ayan-biswas0412** [comment]
> > ci checks are failing please fix
> 
> Checks are failing because i imported a node module how do i include it in the project it is ignored by the commit
> ??

node module folder should be excluded in production please check other ways

**Comment by mohammedjameel24** [comment]
> > > ci checks are failing please fix
> > 
> > Checks are failing because i imported a node module how do i include it in the project it is ignored by the commit
> > ??
> 
> node module folder should be excluded in production please check other ways

So i what way to i import a module ?

**Comment by mohammedjameel24** [comment]
> > > > ci checks are failing please fix
> > > 
> > > Checks are failing because i imported a node module how do i include it in the project it is ignored by the commit
> > > ??
> > 
> > node module folder should be excluded in production please check other ways
> 
> So i what way to i import a module ?

So can i edit a file which is already linked ?

**Comment by mohammedjameel24** [comment]
All Checks have passed , please review and merge my pull request @ayan-biswas0412

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
Iniitally the page becomes dark but not should be light mode initially

**Comment by mohammedjameel24** [comment]
All checks have passed ! the initial light theme is resolved 
kindly review and merge my pull request @ayan-biswas0412

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
kindly edit PR message properly and work is nice

**Comment by mohammedjameel24** [comment]
> kindly edit PR message properly and work is nice

Please edit the template ill fill in accordingly

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Comment by mohammedjameel24** [comment]
Please merge this pull request

**Comment by ayan-biswas0412** [comment]
> Please merge this pull request

will merge it shortly , don't worry

**Pull request merged**
