### PR TITLE
logo added

### PR DESCRIPTION
**Pull request by rajeshpanjiyar**
Fixes #

#### Changes done

- [ ]

Screenshots of the changes (If any) -

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Review by rajeshpanjiyar — COMMENTED** [review]
logo added for HotelOnTouch project under GSSoC'21

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
your logo is showing as empty file

**Comment by rajeshpanjiyar** [comment]
I don't know why it is not showing but it is added. You can see it here:
image

image

Through this, if it is showing so please do inform

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
link the proper issue here and your image file is also not visible

**Comment by rajeshpanjiyar** [comment]
As it is a photo so it is showing an Empty file. So to display it we must click on "display the rich diff" as mentioned below:-

image

**Comment by rajeshpanjiyar** [comment]
Can I get a review on my PR? The logo was a-z as per your command and suggestion.

**Comment by ayan-biswas0412** [comment]
> Can I get a review on my PR? The logo was a-z as per your command and suggestion.

we will merge your PR shortly

**Comment by rajeshpanjiyar** [comment]
Thank very much for hope

**Comment by rajeshpanjiyar** [comment]
> > Can I get a review on my PR? The logo was a-z as per your command and suggestion.
> 
> we will merge your PR shortly

okay:)

**Pull request merged**
