### PR TITLE
fix: Fix reloading problem of different paths

### PR DESCRIPTION
**Pull request by hsnice16**
Fixes #

#### Changes done

-  Created a new folder constants in hotelontouch/src , and a new file constants/routes.js in it 

-  In constants/routes.js , added path for home page and contact page

-  In App.js, instead of hard path, added reference path

-  In NavbarComponent.js, Converted Navbar.Brand and NavDropdown.Item as react-router-dom Link .

Screenshots of the changes (If any) -

image

image

image

image

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
I don't think this is a valid change  you have just declared routes in a separate file and called them nothing else

**Comment by hsnice16** [comment]
the last point of changes done is the change that will prevent from reloading. Navbar.Brand and NavDropdown.Item (of contact us)  will now work **as** react-router-dom **Link**

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
but I don't want any new file constants/route.js just keep them as simple like before

**Comment by hsnice16** [comment]
but this makes it easy to find all possible routes in one place.

**Comment by hsnice16** [comment]
In the third commit #e9cfedb, I tried to squash them in one. But still, it is showing 4 commits.

**Comment by hsnice16** [comment]
Can you please help me, with that? And please merge this PR.

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Comment by hsnice16** [comment]
Thanks for approving it.

**Comment by hsnice16** [comment]
Please merge it.

**Comment by hsnice16** [comment]
@ayan-biswas0412 Please merge it

**Comment by hsnice16** [comment]
@ayan-biswas0412  can you give gssoc and level label to PR, as I think without labels the PR is not countable. Thanks in advance.

**Pull request merged**
