### PR TITLE
Corrections in readme

### LINKED ISSUE #159: Corrections of English grammar, spelling, punctuation errors in the README.md
Hello Mentors , I would be happy to correct some of the English grammar, spelling, punctuation errors in the README.md. Looking forward to working on this issue as a GSSOC 21 participant. Thank you:)

### PR DESCRIPTION
**Pull request by sharvariiii**
docs: Changes to README.md

Fixes #159

#### Changes done

- [1] Corrections of English grammar, spelling, punctuation errors in the README.md

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Comment by sharvariiii** [comment]
> nice work

**Comment by sharvariiii** [comment]
> nice work

Here I can see "Deploy Cancelled". Does it has to be fixed by my side. I don't know how to do it. Will be waiting patiently for your guidance.

**Comment by ayan-biswas0412** [comment]
> > nice work
> 
> Here I can see "Deploy Cancelled". Does it has to be fixed by my side. I don't know how to do it. Will be waiting patiently for your guidance.

no no deploy cancelled is a normal thing

**Comment by sharvariiii** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

why so..I have already opened the PR #162 which fixes this issue.

**Pull request merged**
