### PR TITLE
Added applaunch page, fixes issue #123

### LINKED ISSUE #123: Create a app launching page in hotelontouch
**Is your feature request related to a problem? Please describe.**
make a page /applaunch inside hotelontouch
the page should describe app of hotelontouch you may use cool svgs and make it creative and all components should reside under /components

### PR DESCRIPTION
**Pull request by abhishek7997**
type: fix

Fixes #123 

#### Changes done

- [1] Added AppLaunch.js in components folder
- [2] Added '/applaunch' route in App.js
- [3] Added AppLaunch.js page in '/pages' and in 'index.js'

Screenshots of the changes (If any) -

image
image

Note: Please check Allow edits from maintainers. if you would like us to assist in the PR.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

### CODE REVIEW

**Comment by abhishek7997** [comment]
@ayan-biswas0412 Please check this new PR.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
change theme button is not working properly in your page

**Comment by abhishek7997** [comment]
@ayan-biswas0412 Please check the new commit

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
your component's colour is static that I don't want here😅 please make it dynamic based on theme and also make it fullscreen like earlier and change the colour accordingly

**Comment by abhishek7997** [comment]
@ayan-biswas0412 The problem with the previous setup was that the Theme Change button was hiding behind the container/jumbotron on the app launch page, but I will try if something works or not.

**Comment by abhishek7997** [comment]
@ayan-biswas0412  Please check the new commit

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
change the colour of the texts to white in dark mode

**Comment by abhishek7997** [comment]
@ayan-biswas0412 I am stuck here, the text on app launch page does not change upon toggling the theme, whereas it changes in homepage? Any idea why this is happening?

**Review by ayan-biswas0412 — APPROVED** [review]
nice work

**Comment by abhishek7997** [comment]
> nice work

If it is OK, then please merge the PR.
Thank you.

**Comment by abhishek7997** [comment]
@ayan-biswas0412 Its been at least 2 weeks since the PR was approved. Please give feedback on this PR. Or at least tell whether the PR is okay or not.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
please resolve the conflicts

**Comment by abhishek7997** [comment]
@ayan-biswas0412 Conflicts resolved

**Comment by abhishek7997** [comment]
@ayan-biswas0412 please check the PR now.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
onClick the button 
image 
redirect to the applaunch page

**Comment by abhishek7997** [comment]
@ayan-biswas0412 Can you please tell me how to update my forked repository without losing any changes that I made?

**Pull request closed without merging**
