### PR TITLE
[Backend] Added user schema for admin, employee and customer

### PR DESCRIPTION
**Pull request by singhayushh**
Fixes for Issue #98 

#### Changes done

- [x] Schema for admins, employees and customer added in the file: `model/user.model.js`.
As customer model has additional features than employees and admins, customer schema has been kept separate from the hotel admin and employees.
- [x] I have also added and enabled CORS, which I found missing in the initial express server setup. CORS is needed if the client side and the server side are deployed individually on different ports / hosts to enable interaction between the two. 
> Here's more info about [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), if needed.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [] Tried Squashing the commits into one

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
@singhayushh can you integrate one single template like jsdocs to document the apis such that we can test them by seeing docs

**Comment by singhayushh** [comment]
> @singhayushh can you integrate one single template like jsdocs to document the apis such that we can test them by seeing docs

Yeah definitely I'll do that. 
The current PR doesn't have any endpoints for now. It has the model which is quite important to be finalized before creating APIs. I've documented the model thoroughly and you can trust me on API documentation as well.

**Comment by ayan-biswas0412** [comment]
> > @singhayushh can you integrate one single template like jsdocs to document the apis such that we can test them by seeing docs
> 
> Yeah definitely I'll do that.
> The current PR doesn't have any endpoints for now. It has the model which is quite important to be finalized before creating APIs. I've documented the model thoroughly and you can trust me on API documentation as well.

sure so can make issues on that I will be more than happy then

**Review by ayan-biswas0412 — COMMENTED** [review]
for now the models are good , please strart making CRUD endpoints on them

**Comment by singhayushh** [comment]
@ayan-biswas0412 The end points have been listed in a separate issue. Do I start with them and commit in this PR or shall I wait for this PR to merge/

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 The end points have been listed in a separate issue. Do I start with them and commit in this PR or shall I wait for this PR to merge/

you can checkout from your current (this PR branch) and make your endpoints I will merge that one so it will merge 2 PRs together

**Review by ayan-biswas0412 — APPROVED** [review]
by merging #112 it will be merged automatically

**Pull request merged**
