### PR TITLE
 Backend for food ordering services

### LINKED ISSUE #153: Adding Order Api and Menu
Relate to issue  #147
For Food Odering System , I was thinking of Having of having Order and Menu Order
Order Model will contain:-
- Customer (Object Id)
- Dishes (Array of Object Id of Menu Items)

Menu  Model will contain:-
- DIsh Name
- Dish Price

@ayan-biswas0412  Have a look at issue and I want to work on this

I want to make this functionality using Mongodb and express framework(nodejs )

### PR DESCRIPTION
**Pull request by Sukriti-sood**
…rder Model and also added Controller and routes for same

Fixes #153 

#### Changes done

Added menuItem and order model and also added Controller file nad routes to the same.

#### ✅️ By submitting this PR, I have verified the following

- [x] Worked on forked repo and starred the main repo
- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
ci checks are failing

**Comment by Sukriti-sood** [comment]
> ci checks are failing

@ayan-biswas0412  I am not understanding how to fix this . Can you explain me.

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
can you provide backend path wise test results in screenshot of the PR message

**Comment by Sukriti-sood** [comment]
> can you provide backend path wise test results in screenshot of the PR message

Ook I will update soon.

**Comment by Sukriti-sood** [comment]
Screenshot from 2021-04-10 07-48-53
Screenshot from 2021-04-10 07-49-00
Screenshot from 2021-04-10 11-17-09
Screenshot from 2021-04-10 11-22-30

**Comment by Sukriti-sood** [comment]
@ayan-biswas0412  Please Review my PR

**Pull request closed without merging**
